### ISSUE TITLE
Terraform 0.8.x compatability

### ISSUE THREAD

**Issue by cristobal23** [unifio/terraform-aws-asg#15]
Has anyone tried this module with terraform versions 0.8.x? I got a duplication of resources when using count interpolation for conditional variables.  This is probably due to the change in order of operations for math operators.

**Comment by cristobal23** [comment]
I submitted PR #16 which I hope will address 0.8.x compatibility.

**Comment by pickgr** [comment]
@blakeneyops I think this can be closed now.

**Comment by cristobal23** [comment]
Handled in #18
